
-- meta
CREATE TABLE IF NOT EXISTS g5_saju_meta (
  meta_key VARCHAR(64) PRIMARY KEY,
  meta_value TEXT,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- logs
CREATE TABLE IF NOT EXISTS g5_saju_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  log_type VARCHAR(32) NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  idx1 VARCHAR(64) NULL,
  idx2 VARCHAR(64) NULL,
  KEY(log_type), KEY(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- orders
CREATE TABLE IF NOT EXISTS g5_saju_order (
  od_id INT AUTO_INCREMENT PRIMARY KEY,
  od_uid VARCHAR(32) NOT NULL UNIQUE,
  mb_id VARCHAR(50) NOT NULL DEFAULT '',
  buyer_name VARCHAR(50) NOT NULL,
  buyer_phone VARCHAR(50) NOT NULL,
  buyer_email VARCHAR(120) NOT NULL,
  target_name VARCHAR(50) NOT NULL,
  birth_ymd CHAR(8) NOT NULL,
  birth_time TINYINT NULL,
  is_solar TINYINT NOT NULL DEFAULT 1,
  gender CHAR(1) NOT NULL,
  memo TEXT,
  amount INT NOT NULL DEFAULT 0,
  service_code VARCHAR(50) DEFAULT NULL,
  pg_code VARCHAR(20) NOT NULL DEFAULT 'DUMMY',
  status ENUM('PENDING','PAID','CANCEL','REFUND','DONE') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at DATETIME NULL,
  INDEX(mb_id), INDEX(status), INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- reading
CREATE TABLE IF NOT EXISTS g5_saju_reading (
  rd_id INT AUTO_INCREMENT PRIMARY KEY,
  od_uid VARCHAR(32) NOT NULL,
  mb_id_writer VARCHAR(50) NOT NULL DEFAULT '',
  title VARCHAR(200) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  UNIQUE KEY(od_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- consult
CREATE TABLE IF NOT EXISTS g5_saju_consult (
  cs_id INT AUTO_INCREMENT PRIMARY KEY,
  od_uid VARCHAR(32) NOT NULL,
  writer_type ENUM('USER','ADMIN') NOT NULL,
  mb_id VARCHAR(50) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(od_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- reserve
CREATE TABLE IF NOT EXISTS g5_saju_reserve (
  rv_id INT AUTO_INCREMENT PRIMARY KEY,
  od_uid VARCHAR(32) NOT NULL,
  mb_id VARCHAR(50) NOT NULL DEFAULT '',
  method ENUM('VOICE','VIDEO') NOT NULL,
  rv_date DATE NOT NULL,
  rv_time CHAR(5) NOT NULL,
  price INT NOT NULL DEFAULT 30000,
  status ENUM('REQUEST','PAID','DONE','CANCEL') NOT NULL DEFAULT 'REQUEST',
  meet_url VARCHAR(255) DEFAULT NULL,
  memo VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY(od_uid, rv_date, rv_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- pg map
CREATE TABLE IF NOT EXISTS g5_saju_pgmap (
  map_id INT AUTO_INCREMENT PRIMARY KEY,
  od_uid VARCHAR(32) NOT NULL,
  yc_od_id VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY(od_uid),
  INDEX(yc_od_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- item map (price/service -> it_id)
CREATE TABLE IF NOT EXISTS g5_saju_itemmap (
  map_id INT AUTO_INCREMENT PRIMARY KEY,
  key_type ENUM('PRICE','SERVICE') NOT NULL,
  key_value VARCHAR(100) NOT NULL,
  it_id VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY(key_type, key_value),
  INDEX(it_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
